// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: group.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_group_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_group_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3011000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3011004 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "base.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_group_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_group_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[4]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_group_2eproto;
namespace stark_im {
class CreatGroupReq;
class CreatGroupReqDefaultTypeInternal;
extern CreatGroupReqDefaultTypeInternal _CreatGroupReq_default_instance_;
class CreatGroupRsp;
class CreatGroupRspDefaultTypeInternal;
extern CreatGroupRspDefaultTypeInternal _CreatGroupRsp_default_instance_;
class JoinGroupReq;
class JoinGroupReqDefaultTypeInternal;
extern JoinGroupReqDefaultTypeInternal _JoinGroupReq_default_instance_;
class JoinGroupRsp;
class JoinGroupRspDefaultTypeInternal;
extern JoinGroupRspDefaultTypeInternal _JoinGroupRsp_default_instance_;
}  // namespace stark_im
PROTOBUF_NAMESPACE_OPEN
template<> ::stark_im::CreatGroupReq* Arena::CreateMaybeMessage<::stark_im::CreatGroupReq>(Arena*);
template<> ::stark_im::CreatGroupRsp* Arena::CreateMaybeMessage<::stark_im::CreatGroupRsp>(Arena*);
template<> ::stark_im::JoinGroupReq* Arena::CreateMaybeMessage<::stark_im::JoinGroupReq>(Arena*);
template<> ::stark_im::JoinGroupRsp* Arena::CreateMaybeMessage<::stark_im::JoinGroupRsp>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace stark_im {

// ===================================================================

class CreatGroupReq :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:stark_im.CreatGroupReq) */ {
 public:
  CreatGroupReq();
  virtual ~CreatGroupReq();

  CreatGroupReq(const CreatGroupReq& from);
  CreatGroupReq(CreatGroupReq&& from) noexcept
    : CreatGroupReq() {
    *this = ::std::move(from);
  }

  inline CreatGroupReq& operator=(const CreatGroupReq& from) {
    CopyFrom(from);
    return *this;
  }
  inline CreatGroupReq& operator=(CreatGroupReq&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const CreatGroupReq& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const CreatGroupReq* internal_default_instance() {
    return reinterpret_cast<const CreatGroupReq*>(
               &_CreatGroupReq_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(CreatGroupReq& a, CreatGroupReq& b) {
    a.Swap(&b);
  }
  inline void Swap(CreatGroupReq* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline CreatGroupReq* New() const final {
    return CreateMaybeMessage<CreatGroupReq>(nullptr);
  }

  CreatGroupReq* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<CreatGroupReq>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const CreatGroupReq& from);
  void MergeFrom(const CreatGroupReq& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(CreatGroupReq* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "stark_im.CreatGroupReq";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_group_2eproto);
    return ::descriptor_table_group_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kUseridFieldNumber = 1,
    kGroupnameFieldNumber = 2,
    kDescritionFieldNumber = 3,
  };
  // string userid = 1;
  void clear_userid();
  const std::string& userid() const;
  void set_userid(const std::string& value);
  void set_userid(std::string&& value);
  void set_userid(const char* value);
  void set_userid(const char* value, size_t size);
  std::string* mutable_userid();
  std::string* release_userid();
  void set_allocated_userid(std::string* userid);
  private:
  const std::string& _internal_userid() const;
  void _internal_set_userid(const std::string& value);
  std::string* _internal_mutable_userid();
  public:

  // string groupname = 2;
  void clear_groupname();
  const std::string& groupname() const;
  void set_groupname(const std::string& value);
  void set_groupname(std::string&& value);
  void set_groupname(const char* value);
  void set_groupname(const char* value, size_t size);
  std::string* mutable_groupname();
  std::string* release_groupname();
  void set_allocated_groupname(std::string* groupname);
  private:
  const std::string& _internal_groupname() const;
  void _internal_set_groupname(const std::string& value);
  std::string* _internal_mutable_groupname();
  public:

  // string descrition = 3;
  void clear_descrition();
  const std::string& descrition() const;
  void set_descrition(const std::string& value);
  void set_descrition(std::string&& value);
  void set_descrition(const char* value);
  void set_descrition(const char* value, size_t size);
  std::string* mutable_descrition();
  std::string* release_descrition();
  void set_allocated_descrition(std::string* descrition);
  private:
  const std::string& _internal_descrition() const;
  void _internal_set_descrition(const std::string& value);
  std::string* _internal_mutable_descrition();
  public:

  // @@protoc_insertion_point(class_scope:stark_im.CreatGroupReq)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr userid_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr groupname_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr descrition_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_group_2eproto;
};
// -------------------------------------------------------------------

class CreatGroupRsp :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:stark_im.CreatGroupRsp) */ {
 public:
  CreatGroupRsp();
  virtual ~CreatGroupRsp();

  CreatGroupRsp(const CreatGroupRsp& from);
  CreatGroupRsp(CreatGroupRsp&& from) noexcept
    : CreatGroupRsp() {
    *this = ::std::move(from);
  }

  inline CreatGroupRsp& operator=(const CreatGroupRsp& from) {
    CopyFrom(from);
    return *this;
  }
  inline CreatGroupRsp& operator=(CreatGroupRsp&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const CreatGroupRsp& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const CreatGroupRsp* internal_default_instance() {
    return reinterpret_cast<const CreatGroupRsp*>(
               &_CreatGroupRsp_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(CreatGroupRsp& a, CreatGroupRsp& b) {
    a.Swap(&b);
  }
  inline void Swap(CreatGroupRsp* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline CreatGroupRsp* New() const final {
    return CreateMaybeMessage<CreatGroupRsp>(nullptr);
  }

  CreatGroupRsp* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<CreatGroupRsp>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const CreatGroupRsp& from);
  void MergeFrom(const CreatGroupRsp& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(CreatGroupRsp* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "stark_im.CreatGroupRsp";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_group_2eproto);
    return ::descriptor_table_group_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kErrmsgFieldNumber = 3,
    kGroupidFieldNumber = 4,
    kErrcodeFieldNumber = 2,
    kSuccessFieldNumber = 1,
  };
  // string errmsg = 3;
  void clear_errmsg();
  const std::string& errmsg() const;
  void set_errmsg(const std::string& value);
  void set_errmsg(std::string&& value);
  void set_errmsg(const char* value);
  void set_errmsg(const char* value, size_t size);
  std::string* mutable_errmsg();
  std::string* release_errmsg();
  void set_allocated_errmsg(std::string* errmsg);
  private:
  const std::string& _internal_errmsg() const;
  void _internal_set_errmsg(const std::string& value);
  std::string* _internal_mutable_errmsg();
  public:

  // string groupid = 4;
  void clear_groupid();
  const std::string& groupid() const;
  void set_groupid(const std::string& value);
  void set_groupid(std::string&& value);
  void set_groupid(const char* value);
  void set_groupid(const char* value, size_t size);
  std::string* mutable_groupid();
  std::string* release_groupid();
  void set_allocated_groupid(std::string* groupid);
  private:
  const std::string& _internal_groupid() const;
  void _internal_set_groupid(const std::string& value);
  std::string* _internal_mutable_groupid();
  public:

  // int64 errcode = 2;
  void clear_errcode();
  ::PROTOBUF_NAMESPACE_ID::int64 errcode() const;
  void set_errcode(::PROTOBUF_NAMESPACE_ID::int64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int64 _internal_errcode() const;
  void _internal_set_errcode(::PROTOBUF_NAMESPACE_ID::int64 value);
  public:

  // bool success = 1;
  void clear_success();
  bool success() const;
  void set_success(bool value);
  private:
  bool _internal_success() const;
  void _internal_set_success(bool value);
  public:

  // @@protoc_insertion_point(class_scope:stark_im.CreatGroupRsp)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr errmsg_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr groupid_;
  ::PROTOBUF_NAMESPACE_ID::int64 errcode_;
  bool success_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_group_2eproto;
};
// -------------------------------------------------------------------

class JoinGroupReq :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:stark_im.JoinGroupReq) */ {
 public:
  JoinGroupReq();
  virtual ~JoinGroupReq();

  JoinGroupReq(const JoinGroupReq& from);
  JoinGroupReq(JoinGroupReq&& from) noexcept
    : JoinGroupReq() {
    *this = ::std::move(from);
  }

  inline JoinGroupReq& operator=(const JoinGroupReq& from) {
    CopyFrom(from);
    return *this;
  }
  inline JoinGroupReq& operator=(JoinGroupReq&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const JoinGroupReq& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const JoinGroupReq* internal_default_instance() {
    return reinterpret_cast<const JoinGroupReq*>(
               &_JoinGroupReq_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(JoinGroupReq& a, JoinGroupReq& b) {
    a.Swap(&b);
  }
  inline void Swap(JoinGroupReq* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline JoinGroupReq* New() const final {
    return CreateMaybeMessage<JoinGroupReq>(nullptr);
  }

  JoinGroupReq* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<JoinGroupReq>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const JoinGroupReq& from);
  void MergeFrom(const JoinGroupReq& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(JoinGroupReq* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "stark_im.JoinGroupReq";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_group_2eproto);
    return ::descriptor_table_group_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kUseridFieldNumber = 1,
    kGroupidFieldNumber = 2,
  };
  // string userid = 1;
  void clear_userid();
  const std::string& userid() const;
  void set_userid(const std::string& value);
  void set_userid(std::string&& value);
  void set_userid(const char* value);
  void set_userid(const char* value, size_t size);
  std::string* mutable_userid();
  std::string* release_userid();
  void set_allocated_userid(std::string* userid);
  private:
  const std::string& _internal_userid() const;
  void _internal_set_userid(const std::string& value);
  std::string* _internal_mutable_userid();
  public:

  // string groupid = 2;
  void clear_groupid();
  const std::string& groupid() const;
  void set_groupid(const std::string& value);
  void set_groupid(std::string&& value);
  void set_groupid(const char* value);
  void set_groupid(const char* value, size_t size);
  std::string* mutable_groupid();
  std::string* release_groupid();
  void set_allocated_groupid(std::string* groupid);
  private:
  const std::string& _internal_groupid() const;
  void _internal_set_groupid(const std::string& value);
  std::string* _internal_mutable_groupid();
  public:

  // @@protoc_insertion_point(class_scope:stark_im.JoinGroupReq)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr userid_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr groupid_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_group_2eproto;
};
// -------------------------------------------------------------------

class JoinGroupRsp :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:stark_im.JoinGroupRsp) */ {
 public:
  JoinGroupRsp();
  virtual ~JoinGroupRsp();

  JoinGroupRsp(const JoinGroupRsp& from);
  JoinGroupRsp(JoinGroupRsp&& from) noexcept
    : JoinGroupRsp() {
    *this = ::std::move(from);
  }

  inline JoinGroupRsp& operator=(const JoinGroupRsp& from) {
    CopyFrom(from);
    return *this;
  }
  inline JoinGroupRsp& operator=(JoinGroupRsp&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const JoinGroupRsp& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const JoinGroupRsp* internal_default_instance() {
    return reinterpret_cast<const JoinGroupRsp*>(
               &_JoinGroupRsp_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(JoinGroupRsp& a, JoinGroupRsp& b) {
    a.Swap(&b);
  }
  inline void Swap(JoinGroupRsp* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline JoinGroupRsp* New() const final {
    return CreateMaybeMessage<JoinGroupRsp>(nullptr);
  }

  JoinGroupRsp* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<JoinGroupRsp>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const JoinGroupRsp& from);
  void MergeFrom(const JoinGroupRsp& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(JoinGroupRsp* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "stark_im.JoinGroupRsp";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_group_2eproto);
    return ::descriptor_table_group_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kErrmsgFieldNumber = 3,
    kErrcodeFieldNumber = 2,
    kSuccessFieldNumber = 1,
  };
  // string errmsg = 3;
  void clear_errmsg();
  const std::string& errmsg() const;
  void set_errmsg(const std::string& value);
  void set_errmsg(std::string&& value);
  void set_errmsg(const char* value);
  void set_errmsg(const char* value, size_t size);
  std::string* mutable_errmsg();
  std::string* release_errmsg();
  void set_allocated_errmsg(std::string* errmsg);
  private:
  const std::string& _internal_errmsg() const;
  void _internal_set_errmsg(const std::string& value);
  std::string* _internal_mutable_errmsg();
  public:

  // int64 errcode = 2;
  void clear_errcode();
  ::PROTOBUF_NAMESPACE_ID::int64 errcode() const;
  void set_errcode(::PROTOBUF_NAMESPACE_ID::int64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int64 _internal_errcode() const;
  void _internal_set_errcode(::PROTOBUF_NAMESPACE_ID::int64 value);
  public:

  // bool success = 1;
  void clear_success();
  bool success() const;
  void set_success(bool value);
  private:
  bool _internal_success() const;
  void _internal_set_success(bool value);
  public:

  // @@protoc_insertion_point(class_scope:stark_im.JoinGroupRsp)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr errmsg_;
  ::PROTOBUF_NAMESPACE_ID::int64 errcode_;
  bool success_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_group_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// CreatGroupReq

// string userid = 1;
inline void CreatGroupReq::clear_userid() {
  userid_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline const std::string& CreatGroupReq::userid() const {
  // @@protoc_insertion_point(field_get:stark_im.CreatGroupReq.userid)
  return _internal_userid();
}
inline void CreatGroupReq::set_userid(const std::string& value) {
  _internal_set_userid(value);
  // @@protoc_insertion_point(field_set:stark_im.CreatGroupReq.userid)
}
inline std::string* CreatGroupReq::mutable_userid() {
  // @@protoc_insertion_point(field_mutable:stark_im.CreatGroupReq.userid)
  return _internal_mutable_userid();
}
inline const std::string& CreatGroupReq::_internal_userid() const {
  return userid_.GetNoArena();
}
inline void CreatGroupReq::_internal_set_userid(const std::string& value) {
  
  userid_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
}
inline void CreatGroupReq::set_userid(std::string&& value) {
  
  userid_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:stark_im.CreatGroupReq.userid)
}
inline void CreatGroupReq::set_userid(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  userid_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:stark_im.CreatGroupReq.userid)
}
inline void CreatGroupReq::set_userid(const char* value, size_t size) {
  
  userid_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:stark_im.CreatGroupReq.userid)
}
inline std::string* CreatGroupReq::_internal_mutable_userid() {
  
  return userid_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* CreatGroupReq::release_userid() {
  // @@protoc_insertion_point(field_release:stark_im.CreatGroupReq.userid)
  
  return userid_.ReleaseNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void CreatGroupReq::set_allocated_userid(std::string* userid) {
  if (userid != nullptr) {
    
  } else {
    
  }
  userid_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), userid);
  // @@protoc_insertion_point(field_set_allocated:stark_im.CreatGroupReq.userid)
}

// string groupname = 2;
inline void CreatGroupReq::clear_groupname() {
  groupname_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline const std::string& CreatGroupReq::groupname() const {
  // @@protoc_insertion_point(field_get:stark_im.CreatGroupReq.groupname)
  return _internal_groupname();
}
inline void CreatGroupReq::set_groupname(const std::string& value) {
  _internal_set_groupname(value);
  // @@protoc_insertion_point(field_set:stark_im.CreatGroupReq.groupname)
}
inline std::string* CreatGroupReq::mutable_groupname() {
  // @@protoc_insertion_point(field_mutable:stark_im.CreatGroupReq.groupname)
  return _internal_mutable_groupname();
}
inline const std::string& CreatGroupReq::_internal_groupname() const {
  return groupname_.GetNoArena();
}
inline void CreatGroupReq::_internal_set_groupname(const std::string& value) {
  
  groupname_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
}
inline void CreatGroupReq::set_groupname(std::string&& value) {
  
  groupname_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:stark_im.CreatGroupReq.groupname)
}
inline void CreatGroupReq::set_groupname(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  groupname_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:stark_im.CreatGroupReq.groupname)
}
inline void CreatGroupReq::set_groupname(const char* value, size_t size) {
  
  groupname_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:stark_im.CreatGroupReq.groupname)
}
inline std::string* CreatGroupReq::_internal_mutable_groupname() {
  
  return groupname_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* CreatGroupReq::release_groupname() {
  // @@protoc_insertion_point(field_release:stark_im.CreatGroupReq.groupname)
  
  return groupname_.ReleaseNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void CreatGroupReq::set_allocated_groupname(std::string* groupname) {
  if (groupname != nullptr) {
    
  } else {
    
  }
  groupname_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), groupname);
  // @@protoc_insertion_point(field_set_allocated:stark_im.CreatGroupReq.groupname)
}

// string descrition = 3;
inline void CreatGroupReq::clear_descrition() {
  descrition_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline const std::string& CreatGroupReq::descrition() const {
  // @@protoc_insertion_point(field_get:stark_im.CreatGroupReq.descrition)
  return _internal_descrition();
}
inline void CreatGroupReq::set_descrition(const std::string& value) {
  _internal_set_descrition(value);
  // @@protoc_insertion_point(field_set:stark_im.CreatGroupReq.descrition)
}
inline std::string* CreatGroupReq::mutable_descrition() {
  // @@protoc_insertion_point(field_mutable:stark_im.CreatGroupReq.descrition)
  return _internal_mutable_descrition();
}
inline const std::string& CreatGroupReq::_internal_descrition() const {
  return descrition_.GetNoArena();
}
inline void CreatGroupReq::_internal_set_descrition(const std::string& value) {
  
  descrition_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
}
inline void CreatGroupReq::set_descrition(std::string&& value) {
  
  descrition_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:stark_im.CreatGroupReq.descrition)
}
inline void CreatGroupReq::set_descrition(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  descrition_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:stark_im.CreatGroupReq.descrition)
}
inline void CreatGroupReq::set_descrition(const char* value, size_t size) {
  
  descrition_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:stark_im.CreatGroupReq.descrition)
}
inline std::string* CreatGroupReq::_internal_mutable_descrition() {
  
  return descrition_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* CreatGroupReq::release_descrition() {
  // @@protoc_insertion_point(field_release:stark_im.CreatGroupReq.descrition)
  
  return descrition_.ReleaseNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void CreatGroupReq::set_allocated_descrition(std::string* descrition) {
  if (descrition != nullptr) {
    
  } else {
    
  }
  descrition_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), descrition);
  // @@protoc_insertion_point(field_set_allocated:stark_im.CreatGroupReq.descrition)
}

// -------------------------------------------------------------------

// CreatGroupRsp

// bool success = 1;
inline void CreatGroupRsp::clear_success() {
  success_ = false;
}
inline bool CreatGroupRsp::_internal_success() const {
  return success_;
}
inline bool CreatGroupRsp::success() const {
  // @@protoc_insertion_point(field_get:stark_im.CreatGroupRsp.success)
  return _internal_success();
}
inline void CreatGroupRsp::_internal_set_success(bool value) {
  
  success_ = value;
}
inline void CreatGroupRsp::set_success(bool value) {
  _internal_set_success(value);
  // @@protoc_insertion_point(field_set:stark_im.CreatGroupRsp.success)
}

// int64 errcode = 2;
inline void CreatGroupRsp::clear_errcode() {
  errcode_ = PROTOBUF_LONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::int64 CreatGroupRsp::_internal_errcode() const {
  return errcode_;
}
inline ::PROTOBUF_NAMESPACE_ID::int64 CreatGroupRsp::errcode() const {
  // @@protoc_insertion_point(field_get:stark_im.CreatGroupRsp.errcode)
  return _internal_errcode();
}
inline void CreatGroupRsp::_internal_set_errcode(::PROTOBUF_NAMESPACE_ID::int64 value) {
  
  errcode_ = value;
}
inline void CreatGroupRsp::set_errcode(::PROTOBUF_NAMESPACE_ID::int64 value) {
  _internal_set_errcode(value);
  // @@protoc_insertion_point(field_set:stark_im.CreatGroupRsp.errcode)
}

// string errmsg = 3;
inline void CreatGroupRsp::clear_errmsg() {
  errmsg_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline const std::string& CreatGroupRsp::errmsg() const {
  // @@protoc_insertion_point(field_get:stark_im.CreatGroupRsp.errmsg)
  return _internal_errmsg();
}
inline void CreatGroupRsp::set_errmsg(const std::string& value) {
  _internal_set_errmsg(value);
  // @@protoc_insertion_point(field_set:stark_im.CreatGroupRsp.errmsg)
}
inline std::string* CreatGroupRsp::mutable_errmsg() {
  // @@protoc_insertion_point(field_mutable:stark_im.CreatGroupRsp.errmsg)
  return _internal_mutable_errmsg();
}
inline const std::string& CreatGroupRsp::_internal_errmsg() const {
  return errmsg_.GetNoArena();
}
inline void CreatGroupRsp::_internal_set_errmsg(const std::string& value) {
  
  errmsg_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
}
inline void CreatGroupRsp::set_errmsg(std::string&& value) {
  
  errmsg_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:stark_im.CreatGroupRsp.errmsg)
}
inline void CreatGroupRsp::set_errmsg(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  errmsg_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:stark_im.CreatGroupRsp.errmsg)
}
inline void CreatGroupRsp::set_errmsg(const char* value, size_t size) {
  
  errmsg_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:stark_im.CreatGroupRsp.errmsg)
}
inline std::string* CreatGroupRsp::_internal_mutable_errmsg() {
  
  return errmsg_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* CreatGroupRsp::release_errmsg() {
  // @@protoc_insertion_point(field_release:stark_im.CreatGroupRsp.errmsg)
  
  return errmsg_.ReleaseNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void CreatGroupRsp::set_allocated_errmsg(std::string* errmsg) {
  if (errmsg != nullptr) {
    
  } else {
    
  }
  errmsg_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), errmsg);
  // @@protoc_insertion_point(field_set_allocated:stark_im.CreatGroupRsp.errmsg)
}

// string groupid = 4;
inline void CreatGroupRsp::clear_groupid() {
  groupid_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline const std::string& CreatGroupRsp::groupid() const {
  // @@protoc_insertion_point(field_get:stark_im.CreatGroupRsp.groupid)
  return _internal_groupid();
}
inline void CreatGroupRsp::set_groupid(const std::string& value) {
  _internal_set_groupid(value);
  // @@protoc_insertion_point(field_set:stark_im.CreatGroupRsp.groupid)
}
inline std::string* CreatGroupRsp::mutable_groupid() {
  // @@protoc_insertion_point(field_mutable:stark_im.CreatGroupRsp.groupid)
  return _internal_mutable_groupid();
}
inline const std::string& CreatGroupRsp::_internal_groupid() const {
  return groupid_.GetNoArena();
}
inline void CreatGroupRsp::_internal_set_groupid(const std::string& value) {
  
  groupid_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
}
inline void CreatGroupRsp::set_groupid(std::string&& value) {
  
  groupid_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:stark_im.CreatGroupRsp.groupid)
}
inline void CreatGroupRsp::set_groupid(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  groupid_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:stark_im.CreatGroupRsp.groupid)
}
inline void CreatGroupRsp::set_groupid(const char* value, size_t size) {
  
  groupid_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:stark_im.CreatGroupRsp.groupid)
}
inline std::string* CreatGroupRsp::_internal_mutable_groupid() {
  
  return groupid_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* CreatGroupRsp::release_groupid() {
  // @@protoc_insertion_point(field_release:stark_im.CreatGroupRsp.groupid)
  
  return groupid_.ReleaseNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void CreatGroupRsp::set_allocated_groupid(std::string* groupid) {
  if (groupid != nullptr) {
    
  } else {
    
  }
  groupid_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), groupid);
  // @@protoc_insertion_point(field_set_allocated:stark_im.CreatGroupRsp.groupid)
}

// -------------------------------------------------------------------

// JoinGroupReq

// string userid = 1;
inline void JoinGroupReq::clear_userid() {
  userid_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline const std::string& JoinGroupReq::userid() const {
  // @@protoc_insertion_point(field_get:stark_im.JoinGroupReq.userid)
  return _internal_userid();
}
inline void JoinGroupReq::set_userid(const std::string& value) {
  _internal_set_userid(value);
  // @@protoc_insertion_point(field_set:stark_im.JoinGroupReq.userid)
}
inline std::string* JoinGroupReq::mutable_userid() {
  // @@protoc_insertion_point(field_mutable:stark_im.JoinGroupReq.userid)
  return _internal_mutable_userid();
}
inline const std::string& JoinGroupReq::_internal_userid() const {
  return userid_.GetNoArena();
}
inline void JoinGroupReq::_internal_set_userid(const std::string& value) {
  
  userid_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
}
inline void JoinGroupReq::set_userid(std::string&& value) {
  
  userid_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:stark_im.JoinGroupReq.userid)
}
inline void JoinGroupReq::set_userid(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  userid_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:stark_im.JoinGroupReq.userid)
}
inline void JoinGroupReq::set_userid(const char* value, size_t size) {
  
  userid_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:stark_im.JoinGroupReq.userid)
}
inline std::string* JoinGroupReq::_internal_mutable_userid() {
  
  return userid_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* JoinGroupReq::release_userid() {
  // @@protoc_insertion_point(field_release:stark_im.JoinGroupReq.userid)
  
  return userid_.ReleaseNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void JoinGroupReq::set_allocated_userid(std::string* userid) {
  if (userid != nullptr) {
    
  } else {
    
  }
  userid_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), userid);
  // @@protoc_insertion_point(field_set_allocated:stark_im.JoinGroupReq.userid)
}

// string groupid = 2;
inline void JoinGroupReq::clear_groupid() {
  groupid_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline const std::string& JoinGroupReq::groupid() const {
  // @@protoc_insertion_point(field_get:stark_im.JoinGroupReq.groupid)
  return _internal_groupid();
}
inline void JoinGroupReq::set_groupid(const std::string& value) {
  _internal_set_groupid(value);
  // @@protoc_insertion_point(field_set:stark_im.JoinGroupReq.groupid)
}
inline std::string* JoinGroupReq::mutable_groupid() {
  // @@protoc_insertion_point(field_mutable:stark_im.JoinGroupReq.groupid)
  return _internal_mutable_groupid();
}
inline const std::string& JoinGroupReq::_internal_groupid() const {
  return groupid_.GetNoArena();
}
inline void JoinGroupReq::_internal_set_groupid(const std::string& value) {
  
  groupid_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
}
inline void JoinGroupReq::set_groupid(std::string&& value) {
  
  groupid_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:stark_im.JoinGroupReq.groupid)
}
inline void JoinGroupReq::set_groupid(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  groupid_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:stark_im.JoinGroupReq.groupid)
}
inline void JoinGroupReq::set_groupid(const char* value, size_t size) {
  
  groupid_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:stark_im.JoinGroupReq.groupid)
}
inline std::string* JoinGroupReq::_internal_mutable_groupid() {
  
  return groupid_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* JoinGroupReq::release_groupid() {
  // @@protoc_insertion_point(field_release:stark_im.JoinGroupReq.groupid)
  
  return groupid_.ReleaseNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void JoinGroupReq::set_allocated_groupid(std::string* groupid) {
  if (groupid != nullptr) {
    
  } else {
    
  }
  groupid_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), groupid);
  // @@protoc_insertion_point(field_set_allocated:stark_im.JoinGroupReq.groupid)
}

// -------------------------------------------------------------------

// JoinGroupRsp

// bool success = 1;
inline void JoinGroupRsp::clear_success() {
  success_ = false;
}
inline bool JoinGroupRsp::_internal_success() const {
  return success_;
}
inline bool JoinGroupRsp::success() const {
  // @@protoc_insertion_point(field_get:stark_im.JoinGroupRsp.success)
  return _internal_success();
}
inline void JoinGroupRsp::_internal_set_success(bool value) {
  
  success_ = value;
}
inline void JoinGroupRsp::set_success(bool value) {
  _internal_set_success(value);
  // @@protoc_insertion_point(field_set:stark_im.JoinGroupRsp.success)
}

// int64 errcode = 2;
inline void JoinGroupRsp::clear_errcode() {
  errcode_ = PROTOBUF_LONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::int64 JoinGroupRsp::_internal_errcode() const {
  return errcode_;
}
inline ::PROTOBUF_NAMESPACE_ID::int64 JoinGroupRsp::errcode() const {
  // @@protoc_insertion_point(field_get:stark_im.JoinGroupRsp.errcode)
  return _internal_errcode();
}
inline void JoinGroupRsp::_internal_set_errcode(::PROTOBUF_NAMESPACE_ID::int64 value) {
  
  errcode_ = value;
}
inline void JoinGroupRsp::set_errcode(::PROTOBUF_NAMESPACE_ID::int64 value) {
  _internal_set_errcode(value);
  // @@protoc_insertion_point(field_set:stark_im.JoinGroupRsp.errcode)
}

// string errmsg = 3;
inline void JoinGroupRsp::clear_errmsg() {
  errmsg_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline const std::string& JoinGroupRsp::errmsg() const {
  // @@protoc_insertion_point(field_get:stark_im.JoinGroupRsp.errmsg)
  return _internal_errmsg();
}
inline void JoinGroupRsp::set_errmsg(const std::string& value) {
  _internal_set_errmsg(value);
  // @@protoc_insertion_point(field_set:stark_im.JoinGroupRsp.errmsg)
}
inline std::string* JoinGroupRsp::mutable_errmsg() {
  // @@protoc_insertion_point(field_mutable:stark_im.JoinGroupRsp.errmsg)
  return _internal_mutable_errmsg();
}
inline const std::string& JoinGroupRsp::_internal_errmsg() const {
  return errmsg_.GetNoArena();
}
inline void JoinGroupRsp::_internal_set_errmsg(const std::string& value) {
  
  errmsg_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
}
inline void JoinGroupRsp::set_errmsg(std::string&& value) {
  
  errmsg_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:stark_im.JoinGroupRsp.errmsg)
}
inline void JoinGroupRsp::set_errmsg(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  errmsg_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:stark_im.JoinGroupRsp.errmsg)
}
inline void JoinGroupRsp::set_errmsg(const char* value, size_t size) {
  
  errmsg_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:stark_im.JoinGroupRsp.errmsg)
}
inline std::string* JoinGroupRsp::_internal_mutable_errmsg() {
  
  return errmsg_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* JoinGroupRsp::release_errmsg() {
  // @@protoc_insertion_point(field_release:stark_im.JoinGroupRsp.errmsg)
  
  return errmsg_.ReleaseNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void JoinGroupRsp::set_allocated_errmsg(std::string* errmsg) {
  if (errmsg != nullptr) {
    
  } else {
    
  }
  errmsg_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), errmsg);
  // @@protoc_insertion_point(field_set_allocated:stark_im.JoinGroupRsp.errmsg)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace stark_im

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_group_2eproto
