// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

#include "message.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
extern PROTOBUF_INTERNAL_EXPORT_base_2eproto ::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_MessageInfo_base_2eproto;
namespace stark_im {
class GetOfflineMsgReqDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<GetOfflineMsgReq> _instance;
} _GetOfflineMsgReq_default_instance_;
class GetOfflineMsgRspDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<GetOfflineMsgRsp> _instance;
} _GetOfflineMsgRsp_default_instance_;
class MessageSendReqDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<MessageSendReq> _instance;
} _MessageSendReq_default_instance_;
}  // namespace stark_im
static void InitDefaultsscc_info_GetOfflineMsgReq_message_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::stark_im::_GetOfflineMsgReq_default_instance_;
    new (ptr) ::stark_im::GetOfflineMsgReq();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::stark_im::GetOfflineMsgReq::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_GetOfflineMsgReq_message_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, 0, InitDefaultsscc_info_GetOfflineMsgReq_message_2eproto}, {}};

static void InitDefaultsscc_info_GetOfflineMsgRsp_message_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::stark_im::_GetOfflineMsgRsp_default_instance_;
    new (ptr) ::stark_im::GetOfflineMsgRsp();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::stark_im::GetOfflineMsgRsp::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<1> scc_info_GetOfflineMsgRsp_message_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 1, 0, InitDefaultsscc_info_GetOfflineMsgRsp_message_2eproto}, {
      &scc_info_MessageInfo_base_2eproto.base,}};

static void InitDefaultsscc_info_MessageSendReq_message_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::stark_im::_MessageSendReq_default_instance_;
    new (ptr) ::stark_im::MessageSendReq();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::stark_im::MessageSendReq::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<1> scc_info_MessageSendReq_message_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 1, 0, InitDefaultsscc_info_MessageSendReq_message_2eproto}, {
      &scc_info_MessageInfo_base_2eproto.base,}};

static ::PROTOBUF_NAMESPACE_ID::Metadata file_level_metadata_message_2eproto[3];
static constexpr ::PROTOBUF_NAMESPACE_ID::EnumDescriptor const** file_level_enum_descriptors_message_2eproto = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_message_2eproto = nullptr;

const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_message_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::stark_im::GetOfflineMsgReq, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::stark_im::GetOfflineMsgReq, userid_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::stark_im::GetOfflineMsgRsp, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::stark_im::GetOfflineMsgRsp, success_),
  PROTOBUF_FIELD_OFFSET(::stark_im::GetOfflineMsgRsp, errcode_),
  PROTOBUF_FIELD_OFFSET(::stark_im::GetOfflineMsgRsp, errmsg_),
  PROTOBUF_FIELD_OFFSET(::stark_im::GetOfflineMsgRsp, msglist_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::stark_im::MessageSendReq, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::stark_im::MessageSendReq, msginfo_),
};
static const ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::stark_im::GetOfflineMsgReq)},
  { 6, -1, sizeof(::stark_im::GetOfflineMsgRsp)},
  { 15, -1, sizeof(::stark_im::MessageSendReq)},
};

static ::PROTOBUF_NAMESPACE_ID::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::stark_im::_GetOfflineMsgReq_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::stark_im::_GetOfflineMsgRsp_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::stark_im::_MessageSendReq_default_instance_),
};

const char descriptor_table_protodef_message_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\rmessage.proto\022\010stark_im\032\nbase.proto\"\"\n"
  "\020GetOfflineMsgReq\022\016\n\006userid\030\001 \001(\t\"l\n\020Get"
  "OfflineMsgRsp\022\017\n\007success\030\001 \001(\010\022\017\n\007errcod"
  "e\030\002 \001(\003\022\016\n\006errmsg\030\003 \001(\t\022&\n\007msglist\030\004 \003(\013"
  "2\025.stark_im.MessageInfo\"8\n\016MessageSendRe"
  "q\022&\n\007msginfo\030\001 \001(\0132\025.stark_im.MessageInf"
  "ob\006proto3"
  ;
static const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable*const descriptor_table_message_2eproto_deps[1] = {
  &::descriptor_table_base_2eproto,
};
static ::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase*const descriptor_table_message_2eproto_sccs[3] = {
  &scc_info_GetOfflineMsgReq_message_2eproto.base,
  &scc_info_GetOfflineMsgRsp_message_2eproto.base,
  &scc_info_MessageSendReq_message_2eproto.base,
};
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_message_2eproto_once;
static bool descriptor_table_message_2eproto_initialized = false;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_message_2eproto = {
  &descriptor_table_message_2eproto_initialized, descriptor_table_protodef_message_2eproto, "message.proto", 249,
  &descriptor_table_message_2eproto_once, descriptor_table_message_2eproto_sccs, descriptor_table_message_2eproto_deps, 3, 1,
  schemas, file_default_instances, TableStruct_message_2eproto::offsets,
  file_level_metadata_message_2eproto, 3, file_level_enum_descriptors_message_2eproto, file_level_service_descriptors_message_2eproto,
};

// Force running AddDescriptors() at dynamic initialization time.
static bool dynamic_init_dummy_message_2eproto = (  ::PROTOBUF_NAMESPACE_ID::internal::AddDescriptors(&descriptor_table_message_2eproto), true);
namespace stark_im {

// ===================================================================

void GetOfflineMsgReq::InitAsDefaultInstance() {
}
class GetOfflineMsgReq::_Internal {
 public:
};

GetOfflineMsgReq::GetOfflineMsgReq()
  : ::PROTOBUF_NAMESPACE_ID::Message(), _internal_metadata_(nullptr) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:stark_im.GetOfflineMsgReq)
}
GetOfflineMsgReq::GetOfflineMsgReq(const GetOfflineMsgReq& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      _internal_metadata_(nullptr) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  userid_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_userid().empty()) {
    userid_.AssignWithDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from.userid_);
  }
  // @@protoc_insertion_point(copy_constructor:stark_im.GetOfflineMsgReq)
}

void GetOfflineMsgReq::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_GetOfflineMsgReq_message_2eproto.base);
  userid_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

GetOfflineMsgReq::~GetOfflineMsgReq() {
  // @@protoc_insertion_point(destructor:stark_im.GetOfflineMsgReq)
  SharedDtor();
}

void GetOfflineMsgReq::SharedDtor() {
  userid_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

void GetOfflineMsgReq::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const GetOfflineMsgReq& GetOfflineMsgReq::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_GetOfflineMsgReq_message_2eproto.base);
  return *internal_default_instance();
}


void GetOfflineMsgReq::Clear() {
// @@protoc_insertion_point(message_clear_start:stark_im.GetOfflineMsgReq)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  userid_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  _internal_metadata_.Clear();
}

const char* GetOfflineMsgReq::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // string userid = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 10)) {
          auto str = _internal_mutable_userid();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "stark_im.GetOfflineMsgReq.userid"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag, &_internal_metadata_, ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* GetOfflineMsgReq::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:stark_im.GetOfflineMsgReq)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string userid = 1;
  if (this->userid().size() > 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_userid().data(), static_cast<int>(this->_internal_userid().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "stark_im.GetOfflineMsgReq.userid");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_userid(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:stark_im.GetOfflineMsgReq)
  return target;
}

size_t GetOfflineMsgReq::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:stark_im.GetOfflineMsgReq)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string userid = 1;
  if (this->userid().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_userid());
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void GetOfflineMsgReq::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:stark_im.GetOfflineMsgReq)
  GOOGLE_DCHECK_NE(&from, this);
  const GetOfflineMsgReq* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<GetOfflineMsgReq>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:stark_im.GetOfflineMsgReq)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:stark_im.GetOfflineMsgReq)
    MergeFrom(*source);
  }
}

void GetOfflineMsgReq::MergeFrom(const GetOfflineMsgReq& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:stark_im.GetOfflineMsgReq)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.userid().size() > 0) {

    userid_.AssignWithDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from.userid_);
  }
}

void GetOfflineMsgReq::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:stark_im.GetOfflineMsgReq)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void GetOfflineMsgReq::CopyFrom(const GetOfflineMsgReq& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:stark_im.GetOfflineMsgReq)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool GetOfflineMsgReq::IsInitialized() const {
  return true;
}

void GetOfflineMsgReq::InternalSwap(GetOfflineMsgReq* other) {
  using std::swap;
  _internal_metadata_.Swap(&other->_internal_metadata_);
  userid_.Swap(&other->userid_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
}

::PROTOBUF_NAMESPACE_ID::Metadata GetOfflineMsgReq::GetMetadata() const {
  return GetMetadataStatic();
}


// ===================================================================

void GetOfflineMsgRsp::InitAsDefaultInstance() {
}
class GetOfflineMsgRsp::_Internal {
 public:
};

void GetOfflineMsgRsp::clear_msglist() {
  msglist_.Clear();
}
GetOfflineMsgRsp::GetOfflineMsgRsp()
  : ::PROTOBUF_NAMESPACE_ID::Message(), _internal_metadata_(nullptr) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:stark_im.GetOfflineMsgRsp)
}
GetOfflineMsgRsp::GetOfflineMsgRsp(const GetOfflineMsgRsp& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      _internal_metadata_(nullptr),
      msglist_(from.msglist_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  errmsg_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_errmsg().empty()) {
    errmsg_.AssignWithDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from.errmsg_);
  }
  ::memcpy(&errcode_, &from.errcode_,
    static_cast<size_t>(reinterpret_cast<char*>(&success_) -
    reinterpret_cast<char*>(&errcode_)) + sizeof(success_));
  // @@protoc_insertion_point(copy_constructor:stark_im.GetOfflineMsgRsp)
}

void GetOfflineMsgRsp::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_GetOfflineMsgRsp_message_2eproto.base);
  errmsg_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  ::memset(&errcode_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&success_) -
      reinterpret_cast<char*>(&errcode_)) + sizeof(success_));
}

GetOfflineMsgRsp::~GetOfflineMsgRsp() {
  // @@protoc_insertion_point(destructor:stark_im.GetOfflineMsgRsp)
  SharedDtor();
}

void GetOfflineMsgRsp::SharedDtor() {
  errmsg_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

void GetOfflineMsgRsp::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const GetOfflineMsgRsp& GetOfflineMsgRsp::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_GetOfflineMsgRsp_message_2eproto.base);
  return *internal_default_instance();
}


void GetOfflineMsgRsp::Clear() {
// @@protoc_insertion_point(message_clear_start:stark_im.GetOfflineMsgRsp)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  msglist_.Clear();
  errmsg_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  ::memset(&errcode_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&success_) -
      reinterpret_cast<char*>(&errcode_)) + sizeof(success_));
  _internal_metadata_.Clear();
}

const char* GetOfflineMsgRsp::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // bool success = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 8)) {
          success_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // int64 errcode = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 16)) {
          errcode_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // string errmsg = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 26)) {
          auto str = _internal_mutable_errmsg();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "stark_im.GetOfflineMsgRsp.errmsg"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // repeated .stark_im.MessageInfo msglist = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 34)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_msglist(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<34>(ptr));
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag, &_internal_metadata_, ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* GetOfflineMsgRsp::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:stark_im.GetOfflineMsgRsp)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // bool success = 1;
  if (this->success() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteBoolToArray(1, this->_internal_success(), target);
  }

  // int64 errcode = 2;
  if (this->errcode() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt64ToArray(2, this->_internal_errcode(), target);
  }

  // string errmsg = 3;
  if (this->errmsg().size() > 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_errmsg().data(), static_cast<int>(this->_internal_errmsg().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "stark_im.GetOfflineMsgRsp.errmsg");
    target = stream->WriteStringMaybeAliased(
        3, this->_internal_errmsg(), target);
  }

  // repeated .stark_im.MessageInfo msglist = 4;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->_internal_msglist_size()); i < n; i++) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(4, this->_internal_msglist(i), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:stark_im.GetOfflineMsgRsp)
  return target;
}

size_t GetOfflineMsgRsp::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:stark_im.GetOfflineMsgRsp)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .stark_im.MessageInfo msglist = 4;
  total_size += 1UL * this->_internal_msglist_size();
  for (const auto& msg : this->msglist_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  // string errmsg = 3;
  if (this->errmsg().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_errmsg());
  }

  // int64 errcode = 2;
  if (this->errcode() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int64Size(
        this->_internal_errcode());
  }

  // bool success = 1;
  if (this->success() != 0) {
    total_size += 1 + 1;
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void GetOfflineMsgRsp::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:stark_im.GetOfflineMsgRsp)
  GOOGLE_DCHECK_NE(&from, this);
  const GetOfflineMsgRsp* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<GetOfflineMsgRsp>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:stark_im.GetOfflineMsgRsp)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:stark_im.GetOfflineMsgRsp)
    MergeFrom(*source);
  }
}

void GetOfflineMsgRsp::MergeFrom(const GetOfflineMsgRsp& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:stark_im.GetOfflineMsgRsp)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  msglist_.MergeFrom(from.msglist_);
  if (from.errmsg().size() > 0) {

    errmsg_.AssignWithDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from.errmsg_);
  }
  if (from.errcode() != 0) {
    _internal_set_errcode(from._internal_errcode());
  }
  if (from.success() != 0) {
    _internal_set_success(from._internal_success());
  }
}

void GetOfflineMsgRsp::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:stark_im.GetOfflineMsgRsp)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void GetOfflineMsgRsp::CopyFrom(const GetOfflineMsgRsp& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:stark_im.GetOfflineMsgRsp)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool GetOfflineMsgRsp::IsInitialized() const {
  return true;
}

void GetOfflineMsgRsp::InternalSwap(GetOfflineMsgRsp* other) {
  using std::swap;
  _internal_metadata_.Swap(&other->_internal_metadata_);
  msglist_.InternalSwap(&other->msglist_);
  errmsg_.Swap(&other->errmsg_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  swap(errcode_, other->errcode_);
  swap(success_, other->success_);
}

::PROTOBUF_NAMESPACE_ID::Metadata GetOfflineMsgRsp::GetMetadata() const {
  return GetMetadataStatic();
}


// ===================================================================

void MessageSendReq::InitAsDefaultInstance() {
  ::stark_im::_MessageSendReq_default_instance_._instance.get_mutable()->msginfo_ = const_cast< ::stark_im::MessageInfo*>(
      ::stark_im::MessageInfo::internal_default_instance());
}
class MessageSendReq::_Internal {
 public:
  static const ::stark_im::MessageInfo& msginfo(const MessageSendReq* msg);
};

const ::stark_im::MessageInfo&
MessageSendReq::_Internal::msginfo(const MessageSendReq* msg) {
  return *msg->msginfo_;
}
void MessageSendReq::clear_msginfo() {
  if (GetArenaNoVirtual() == nullptr && msginfo_ != nullptr) {
    delete msginfo_;
  }
  msginfo_ = nullptr;
}
MessageSendReq::MessageSendReq()
  : ::PROTOBUF_NAMESPACE_ID::Message(), _internal_metadata_(nullptr) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:stark_im.MessageSendReq)
}
MessageSendReq::MessageSendReq(const MessageSendReq& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      _internal_metadata_(nullptr) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  if (from._internal_has_msginfo()) {
    msginfo_ = new ::stark_im::MessageInfo(*from.msginfo_);
  } else {
    msginfo_ = nullptr;
  }
  // @@protoc_insertion_point(copy_constructor:stark_im.MessageSendReq)
}

void MessageSendReq::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_MessageSendReq_message_2eproto.base);
  msginfo_ = nullptr;
}

MessageSendReq::~MessageSendReq() {
  // @@protoc_insertion_point(destructor:stark_im.MessageSendReq)
  SharedDtor();
}

void MessageSendReq::SharedDtor() {
  if (this != internal_default_instance()) delete msginfo_;
}

void MessageSendReq::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const MessageSendReq& MessageSendReq::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_MessageSendReq_message_2eproto.base);
  return *internal_default_instance();
}


void MessageSendReq::Clear() {
// @@protoc_insertion_point(message_clear_start:stark_im.MessageSendReq)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  if (GetArenaNoVirtual() == nullptr && msginfo_ != nullptr) {
    delete msginfo_;
  }
  msginfo_ = nullptr;
  _internal_metadata_.Clear();
}

const char* MessageSendReq::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // .stark_im.MessageInfo msginfo = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 10)) {
          ptr = ctx->ParseMessage(_internal_mutable_msginfo(), ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag, &_internal_metadata_, ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* MessageSendReq::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:stark_im.MessageSendReq)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .stark_im.MessageInfo msginfo = 1;
  if (this->has_msginfo()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        1, _Internal::msginfo(this), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:stark_im.MessageSendReq)
  return target;
}

size_t MessageSendReq::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:stark_im.MessageSendReq)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // .stark_im.MessageInfo msginfo = 1;
  if (this->has_msginfo()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *msginfo_);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void MessageSendReq::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:stark_im.MessageSendReq)
  GOOGLE_DCHECK_NE(&from, this);
  const MessageSendReq* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<MessageSendReq>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:stark_im.MessageSendReq)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:stark_im.MessageSendReq)
    MergeFrom(*source);
  }
}

void MessageSendReq::MergeFrom(const MessageSendReq& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:stark_im.MessageSendReq)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.has_msginfo()) {
    _internal_mutable_msginfo()->::stark_im::MessageInfo::MergeFrom(from._internal_msginfo());
  }
}

void MessageSendReq::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:stark_im.MessageSendReq)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void MessageSendReq::CopyFrom(const MessageSendReq& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:stark_im.MessageSendReq)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool MessageSendReq::IsInitialized() const {
  return true;
}

void MessageSendReq::InternalSwap(MessageSendReq* other) {
  using std::swap;
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(msginfo_, other->msginfo_);
}

::PROTOBUF_NAMESPACE_ID::Metadata MessageSendReq::GetMetadata() const {
  return GetMetadataStatic();
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace stark_im
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::stark_im::GetOfflineMsgReq* Arena::CreateMaybeMessage< ::stark_im::GetOfflineMsgReq >(Arena* arena) {
  return Arena::CreateInternal< ::stark_im::GetOfflineMsgReq >(arena);
}
template<> PROTOBUF_NOINLINE ::stark_im::GetOfflineMsgRsp* Arena::CreateMaybeMessage< ::stark_im::GetOfflineMsgRsp >(Arena* arena) {
  return Arena::CreateInternal< ::stark_im::GetOfflineMsgRsp >(arena);
}
template<> PROTOBUF_NOINLINE ::stark_im::MessageSendReq* Arena::CreateMaybeMessage< ::stark_im::MessageSendReq >(Arena* arena) {
  return Arena::CreateInternal< ::stark_im::MessageSendReq >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
