// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_message_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_message_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3011000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3011004 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "base.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_message_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_message_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[3]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_message_2eproto;
namespace stark_im {
class GetOfflineMsgReq;
class GetOfflineMsgReqDefaultTypeInternal;
extern GetOfflineMsgReqDefaultTypeInternal _GetOfflineMsgReq_default_instance_;
class GetOfflineMsgRsp;
class GetOfflineMsgRspDefaultTypeInternal;
extern GetOfflineMsgRspDefaultTypeInternal _GetOfflineMsgRsp_default_instance_;
class MessageSendReq;
class MessageSendReqDefaultTypeInternal;
extern MessageSendReqDefaultTypeInternal _MessageSendReq_default_instance_;
}  // namespace stark_im
PROTOBUF_NAMESPACE_OPEN
template<> ::stark_im::GetOfflineMsgReq* Arena::CreateMaybeMessage<::stark_im::GetOfflineMsgReq>(Arena*);
template<> ::stark_im::GetOfflineMsgRsp* Arena::CreateMaybeMessage<::stark_im::GetOfflineMsgRsp>(Arena*);
template<> ::stark_im::MessageSendReq* Arena::CreateMaybeMessage<::stark_im::MessageSendReq>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace stark_im {

// ===================================================================

class GetOfflineMsgReq :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:stark_im.GetOfflineMsgReq) */ {
 public:
  GetOfflineMsgReq();
  virtual ~GetOfflineMsgReq();

  GetOfflineMsgReq(const GetOfflineMsgReq& from);
  GetOfflineMsgReq(GetOfflineMsgReq&& from) noexcept
    : GetOfflineMsgReq() {
    *this = ::std::move(from);
  }

  inline GetOfflineMsgReq& operator=(const GetOfflineMsgReq& from) {
    CopyFrom(from);
    return *this;
  }
  inline GetOfflineMsgReq& operator=(GetOfflineMsgReq&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const GetOfflineMsgReq& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const GetOfflineMsgReq* internal_default_instance() {
    return reinterpret_cast<const GetOfflineMsgReq*>(
               &_GetOfflineMsgReq_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(GetOfflineMsgReq& a, GetOfflineMsgReq& b) {
    a.Swap(&b);
  }
  inline void Swap(GetOfflineMsgReq* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline GetOfflineMsgReq* New() const final {
    return CreateMaybeMessage<GetOfflineMsgReq>(nullptr);
  }

  GetOfflineMsgReq* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<GetOfflineMsgReq>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const GetOfflineMsgReq& from);
  void MergeFrom(const GetOfflineMsgReq& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(GetOfflineMsgReq* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "stark_im.GetOfflineMsgReq";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_message_2eproto);
    return ::descriptor_table_message_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kUseridFieldNumber = 1,
  };
  // string userid = 1;
  void clear_userid();
  const std::string& userid() const;
  void set_userid(const std::string& value);
  void set_userid(std::string&& value);
  void set_userid(const char* value);
  void set_userid(const char* value, size_t size);
  std::string* mutable_userid();
  std::string* release_userid();
  void set_allocated_userid(std::string* userid);
  private:
  const std::string& _internal_userid() const;
  void _internal_set_userid(const std::string& value);
  std::string* _internal_mutable_userid();
  public:

  // @@protoc_insertion_point(class_scope:stark_im.GetOfflineMsgReq)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr userid_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_message_2eproto;
};
// -------------------------------------------------------------------

class GetOfflineMsgRsp :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:stark_im.GetOfflineMsgRsp) */ {
 public:
  GetOfflineMsgRsp();
  virtual ~GetOfflineMsgRsp();

  GetOfflineMsgRsp(const GetOfflineMsgRsp& from);
  GetOfflineMsgRsp(GetOfflineMsgRsp&& from) noexcept
    : GetOfflineMsgRsp() {
    *this = ::std::move(from);
  }

  inline GetOfflineMsgRsp& operator=(const GetOfflineMsgRsp& from) {
    CopyFrom(from);
    return *this;
  }
  inline GetOfflineMsgRsp& operator=(GetOfflineMsgRsp&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const GetOfflineMsgRsp& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const GetOfflineMsgRsp* internal_default_instance() {
    return reinterpret_cast<const GetOfflineMsgRsp*>(
               &_GetOfflineMsgRsp_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(GetOfflineMsgRsp& a, GetOfflineMsgRsp& b) {
    a.Swap(&b);
  }
  inline void Swap(GetOfflineMsgRsp* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline GetOfflineMsgRsp* New() const final {
    return CreateMaybeMessage<GetOfflineMsgRsp>(nullptr);
  }

  GetOfflineMsgRsp* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<GetOfflineMsgRsp>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const GetOfflineMsgRsp& from);
  void MergeFrom(const GetOfflineMsgRsp& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(GetOfflineMsgRsp* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "stark_im.GetOfflineMsgRsp";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_message_2eproto);
    return ::descriptor_table_message_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kMsglistFieldNumber = 4,
    kErrmsgFieldNumber = 3,
    kErrcodeFieldNumber = 2,
    kSuccessFieldNumber = 1,
  };
  // repeated .stark_im.MessageInfo msglist = 4;
  int msglist_size() const;
  private:
  int _internal_msglist_size() const;
  public:
  void clear_msglist();
  ::stark_im::MessageInfo* mutable_msglist(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::stark_im::MessageInfo >*
      mutable_msglist();
  private:
  const ::stark_im::MessageInfo& _internal_msglist(int index) const;
  ::stark_im::MessageInfo* _internal_add_msglist();
  public:
  const ::stark_im::MessageInfo& msglist(int index) const;
  ::stark_im::MessageInfo* add_msglist();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::stark_im::MessageInfo >&
      msglist() const;

  // string errmsg = 3;
  void clear_errmsg();
  const std::string& errmsg() const;
  void set_errmsg(const std::string& value);
  void set_errmsg(std::string&& value);
  void set_errmsg(const char* value);
  void set_errmsg(const char* value, size_t size);
  std::string* mutable_errmsg();
  std::string* release_errmsg();
  void set_allocated_errmsg(std::string* errmsg);
  private:
  const std::string& _internal_errmsg() const;
  void _internal_set_errmsg(const std::string& value);
  std::string* _internal_mutable_errmsg();
  public:

  // int64 errcode = 2;
  void clear_errcode();
  ::PROTOBUF_NAMESPACE_ID::int64 errcode() const;
  void set_errcode(::PROTOBUF_NAMESPACE_ID::int64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int64 _internal_errcode() const;
  void _internal_set_errcode(::PROTOBUF_NAMESPACE_ID::int64 value);
  public:

  // bool success = 1;
  void clear_success();
  bool success() const;
  void set_success(bool value);
  private:
  bool _internal_success() const;
  void _internal_set_success(bool value);
  public:

  // @@protoc_insertion_point(class_scope:stark_im.GetOfflineMsgRsp)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::stark_im::MessageInfo > msglist_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr errmsg_;
  ::PROTOBUF_NAMESPACE_ID::int64 errcode_;
  bool success_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_message_2eproto;
};
// -------------------------------------------------------------------

class MessageSendReq :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:stark_im.MessageSendReq) */ {
 public:
  MessageSendReq();
  virtual ~MessageSendReq();

  MessageSendReq(const MessageSendReq& from);
  MessageSendReq(MessageSendReq&& from) noexcept
    : MessageSendReq() {
    *this = ::std::move(from);
  }

  inline MessageSendReq& operator=(const MessageSendReq& from) {
    CopyFrom(from);
    return *this;
  }
  inline MessageSendReq& operator=(MessageSendReq&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const MessageSendReq& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const MessageSendReq* internal_default_instance() {
    return reinterpret_cast<const MessageSendReq*>(
               &_MessageSendReq_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(MessageSendReq& a, MessageSendReq& b) {
    a.Swap(&b);
  }
  inline void Swap(MessageSendReq* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline MessageSendReq* New() const final {
    return CreateMaybeMessage<MessageSendReq>(nullptr);
  }

  MessageSendReq* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<MessageSendReq>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const MessageSendReq& from);
  void MergeFrom(const MessageSendReq& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(MessageSendReq* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "stark_im.MessageSendReq";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_message_2eproto);
    return ::descriptor_table_message_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kMsginfoFieldNumber = 1,
  };
  // .stark_im.MessageInfo msginfo = 1;
  bool has_msginfo() const;
  private:
  bool _internal_has_msginfo() const;
  public:
  void clear_msginfo();
  const ::stark_im::MessageInfo& msginfo() const;
  ::stark_im::MessageInfo* release_msginfo();
  ::stark_im::MessageInfo* mutable_msginfo();
  void set_allocated_msginfo(::stark_im::MessageInfo* msginfo);
  private:
  const ::stark_im::MessageInfo& _internal_msginfo() const;
  ::stark_im::MessageInfo* _internal_mutable_msginfo();
  public:

  // @@protoc_insertion_point(class_scope:stark_im.MessageSendReq)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::stark_im::MessageInfo* msginfo_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_message_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// GetOfflineMsgReq

// string userid = 1;
inline void GetOfflineMsgReq::clear_userid() {
  userid_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline const std::string& GetOfflineMsgReq::userid() const {
  // @@protoc_insertion_point(field_get:stark_im.GetOfflineMsgReq.userid)
  return _internal_userid();
}
inline void GetOfflineMsgReq::set_userid(const std::string& value) {
  _internal_set_userid(value);
  // @@protoc_insertion_point(field_set:stark_im.GetOfflineMsgReq.userid)
}
inline std::string* GetOfflineMsgReq::mutable_userid() {
  // @@protoc_insertion_point(field_mutable:stark_im.GetOfflineMsgReq.userid)
  return _internal_mutable_userid();
}
inline const std::string& GetOfflineMsgReq::_internal_userid() const {
  return userid_.GetNoArena();
}
inline void GetOfflineMsgReq::_internal_set_userid(const std::string& value) {
  
  userid_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
}
inline void GetOfflineMsgReq::set_userid(std::string&& value) {
  
  userid_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:stark_im.GetOfflineMsgReq.userid)
}
inline void GetOfflineMsgReq::set_userid(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  userid_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:stark_im.GetOfflineMsgReq.userid)
}
inline void GetOfflineMsgReq::set_userid(const char* value, size_t size) {
  
  userid_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:stark_im.GetOfflineMsgReq.userid)
}
inline std::string* GetOfflineMsgReq::_internal_mutable_userid() {
  
  return userid_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* GetOfflineMsgReq::release_userid() {
  // @@protoc_insertion_point(field_release:stark_im.GetOfflineMsgReq.userid)
  
  return userid_.ReleaseNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void GetOfflineMsgReq::set_allocated_userid(std::string* userid) {
  if (userid != nullptr) {
    
  } else {
    
  }
  userid_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), userid);
  // @@protoc_insertion_point(field_set_allocated:stark_im.GetOfflineMsgReq.userid)
}

// -------------------------------------------------------------------

// GetOfflineMsgRsp

// bool success = 1;
inline void GetOfflineMsgRsp::clear_success() {
  success_ = false;
}
inline bool GetOfflineMsgRsp::_internal_success() const {
  return success_;
}
inline bool GetOfflineMsgRsp::success() const {
  // @@protoc_insertion_point(field_get:stark_im.GetOfflineMsgRsp.success)
  return _internal_success();
}
inline void GetOfflineMsgRsp::_internal_set_success(bool value) {
  
  success_ = value;
}
inline void GetOfflineMsgRsp::set_success(bool value) {
  _internal_set_success(value);
  // @@protoc_insertion_point(field_set:stark_im.GetOfflineMsgRsp.success)
}

// int64 errcode = 2;
inline void GetOfflineMsgRsp::clear_errcode() {
  errcode_ = PROTOBUF_LONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::int64 GetOfflineMsgRsp::_internal_errcode() const {
  return errcode_;
}
inline ::PROTOBUF_NAMESPACE_ID::int64 GetOfflineMsgRsp::errcode() const {
  // @@protoc_insertion_point(field_get:stark_im.GetOfflineMsgRsp.errcode)
  return _internal_errcode();
}
inline void GetOfflineMsgRsp::_internal_set_errcode(::PROTOBUF_NAMESPACE_ID::int64 value) {
  
  errcode_ = value;
}
inline void GetOfflineMsgRsp::set_errcode(::PROTOBUF_NAMESPACE_ID::int64 value) {
  _internal_set_errcode(value);
  // @@protoc_insertion_point(field_set:stark_im.GetOfflineMsgRsp.errcode)
}

// string errmsg = 3;
inline void GetOfflineMsgRsp::clear_errmsg() {
  errmsg_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline const std::string& GetOfflineMsgRsp::errmsg() const {
  // @@protoc_insertion_point(field_get:stark_im.GetOfflineMsgRsp.errmsg)
  return _internal_errmsg();
}
inline void GetOfflineMsgRsp::set_errmsg(const std::string& value) {
  _internal_set_errmsg(value);
  // @@protoc_insertion_point(field_set:stark_im.GetOfflineMsgRsp.errmsg)
}
inline std::string* GetOfflineMsgRsp::mutable_errmsg() {
  // @@protoc_insertion_point(field_mutable:stark_im.GetOfflineMsgRsp.errmsg)
  return _internal_mutable_errmsg();
}
inline const std::string& GetOfflineMsgRsp::_internal_errmsg() const {
  return errmsg_.GetNoArena();
}
inline void GetOfflineMsgRsp::_internal_set_errmsg(const std::string& value) {
  
  errmsg_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
}
inline void GetOfflineMsgRsp::set_errmsg(std::string&& value) {
  
  errmsg_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:stark_im.GetOfflineMsgRsp.errmsg)
}
inline void GetOfflineMsgRsp::set_errmsg(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  errmsg_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:stark_im.GetOfflineMsgRsp.errmsg)
}
inline void GetOfflineMsgRsp::set_errmsg(const char* value, size_t size) {
  
  errmsg_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:stark_im.GetOfflineMsgRsp.errmsg)
}
inline std::string* GetOfflineMsgRsp::_internal_mutable_errmsg() {
  
  return errmsg_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* GetOfflineMsgRsp::release_errmsg() {
  // @@protoc_insertion_point(field_release:stark_im.GetOfflineMsgRsp.errmsg)
  
  return errmsg_.ReleaseNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void GetOfflineMsgRsp::set_allocated_errmsg(std::string* errmsg) {
  if (errmsg != nullptr) {
    
  } else {
    
  }
  errmsg_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), errmsg);
  // @@protoc_insertion_point(field_set_allocated:stark_im.GetOfflineMsgRsp.errmsg)
}

// repeated .stark_im.MessageInfo msglist = 4;
inline int GetOfflineMsgRsp::_internal_msglist_size() const {
  return msglist_.size();
}
inline int GetOfflineMsgRsp::msglist_size() const {
  return _internal_msglist_size();
}
inline ::stark_im::MessageInfo* GetOfflineMsgRsp::mutable_msglist(int index) {
  // @@protoc_insertion_point(field_mutable:stark_im.GetOfflineMsgRsp.msglist)
  return msglist_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::stark_im::MessageInfo >*
GetOfflineMsgRsp::mutable_msglist() {
  // @@protoc_insertion_point(field_mutable_list:stark_im.GetOfflineMsgRsp.msglist)
  return &msglist_;
}
inline const ::stark_im::MessageInfo& GetOfflineMsgRsp::_internal_msglist(int index) const {
  return msglist_.Get(index);
}
inline const ::stark_im::MessageInfo& GetOfflineMsgRsp::msglist(int index) const {
  // @@protoc_insertion_point(field_get:stark_im.GetOfflineMsgRsp.msglist)
  return _internal_msglist(index);
}
inline ::stark_im::MessageInfo* GetOfflineMsgRsp::_internal_add_msglist() {
  return msglist_.Add();
}
inline ::stark_im::MessageInfo* GetOfflineMsgRsp::add_msglist() {
  // @@protoc_insertion_point(field_add:stark_im.GetOfflineMsgRsp.msglist)
  return _internal_add_msglist();
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::stark_im::MessageInfo >&
GetOfflineMsgRsp::msglist() const {
  // @@protoc_insertion_point(field_list:stark_im.GetOfflineMsgRsp.msglist)
  return msglist_;
}

// -------------------------------------------------------------------

// MessageSendReq

// .stark_im.MessageInfo msginfo = 1;
inline bool MessageSendReq::_internal_has_msginfo() const {
  return this != internal_default_instance() && msginfo_ != nullptr;
}
inline bool MessageSendReq::has_msginfo() const {
  return _internal_has_msginfo();
}
inline const ::stark_im::MessageInfo& MessageSendReq::_internal_msginfo() const {
  const ::stark_im::MessageInfo* p = msginfo_;
  return p != nullptr ? *p : *reinterpret_cast<const ::stark_im::MessageInfo*>(
      &::stark_im::_MessageInfo_default_instance_);
}
inline const ::stark_im::MessageInfo& MessageSendReq::msginfo() const {
  // @@protoc_insertion_point(field_get:stark_im.MessageSendReq.msginfo)
  return _internal_msginfo();
}
inline ::stark_im::MessageInfo* MessageSendReq::release_msginfo() {
  // @@protoc_insertion_point(field_release:stark_im.MessageSendReq.msginfo)
  
  ::stark_im::MessageInfo* temp = msginfo_;
  msginfo_ = nullptr;
  return temp;
}
inline ::stark_im::MessageInfo* MessageSendReq::_internal_mutable_msginfo() {
  
  if (msginfo_ == nullptr) {
    auto* p = CreateMaybeMessage<::stark_im::MessageInfo>(GetArenaNoVirtual());
    msginfo_ = p;
  }
  return msginfo_;
}
inline ::stark_im::MessageInfo* MessageSendReq::mutable_msginfo() {
  // @@protoc_insertion_point(field_mutable:stark_im.MessageSendReq.msginfo)
  return _internal_mutable_msginfo();
}
inline void MessageSendReq::set_allocated_msginfo(::stark_im::MessageInfo* msginfo) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(msginfo_);
  }
  if (msginfo) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena = nullptr;
    if (message_arena != submessage_arena) {
      msginfo = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, msginfo, submessage_arena);
    }
    
  } else {
    
  }
  msginfo_ = msginfo;
  // @@protoc_insertion_point(field_set_allocated:stark_im.MessageSendReq.msginfo)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace stark_im

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_message_2eproto
