// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: notify.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_notify_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_notify_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3011000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3011004 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "base.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_notify_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_notify_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[1]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_notify_2eproto;
namespace stark_im {
class NotifyNewMessage;
class NotifyNewMessageDefaultTypeInternal;
extern NotifyNewMessageDefaultTypeInternal _NotifyNewMessage_default_instance_;
}  // namespace stark_im
PROTOBUF_NAMESPACE_OPEN
template<> ::stark_im::NotifyNewMessage* Arena::CreateMaybeMessage<::stark_im::NotifyNewMessage>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace stark_im {

// ===================================================================

class NotifyNewMessage :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:stark_im.NotifyNewMessage) */ {
 public:
  NotifyNewMessage();
  virtual ~NotifyNewMessage();

  NotifyNewMessage(const NotifyNewMessage& from);
  NotifyNewMessage(NotifyNewMessage&& from) noexcept
    : NotifyNewMessage() {
    *this = ::std::move(from);
  }

  inline NotifyNewMessage& operator=(const NotifyNewMessage& from) {
    CopyFrom(from);
    return *this;
  }
  inline NotifyNewMessage& operator=(NotifyNewMessage&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const NotifyNewMessage& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const NotifyNewMessage* internal_default_instance() {
    return reinterpret_cast<const NotifyNewMessage*>(
               &_NotifyNewMessage_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(NotifyNewMessage& a, NotifyNewMessage& b) {
    a.Swap(&b);
  }
  inline void Swap(NotifyNewMessage* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline NotifyNewMessage* New() const final {
    return CreateMaybeMessage<NotifyNewMessage>(nullptr);
  }

  NotifyNewMessage* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<NotifyNewMessage>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const NotifyNewMessage& from);
  void MergeFrom(const NotifyNewMessage& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(NotifyNewMessage* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "stark_im.NotifyNewMessage";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_notify_2eproto);
    return ::descriptor_table_notify_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kMsginfoFieldNumber = 1,
  };
  // .stark_im.MessageInfo msginfo = 1;
  bool has_msginfo() const;
  private:
  bool _internal_has_msginfo() const;
  public:
  void clear_msginfo();
  const ::stark_im::MessageInfo& msginfo() const;
  ::stark_im::MessageInfo* release_msginfo();
  ::stark_im::MessageInfo* mutable_msginfo();
  void set_allocated_msginfo(::stark_im::MessageInfo* msginfo);
  private:
  const ::stark_im::MessageInfo& _internal_msginfo() const;
  ::stark_im::MessageInfo* _internal_mutable_msginfo();
  public:

  // @@protoc_insertion_point(class_scope:stark_im.NotifyNewMessage)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::stark_im::MessageInfo* msginfo_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_notify_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// NotifyNewMessage

// .stark_im.MessageInfo msginfo = 1;
inline bool NotifyNewMessage::_internal_has_msginfo() const {
  return this != internal_default_instance() && msginfo_ != nullptr;
}
inline bool NotifyNewMessage::has_msginfo() const {
  return _internal_has_msginfo();
}
inline const ::stark_im::MessageInfo& NotifyNewMessage::_internal_msginfo() const {
  const ::stark_im::MessageInfo* p = msginfo_;
  return p != nullptr ? *p : *reinterpret_cast<const ::stark_im::MessageInfo*>(
      &::stark_im::_MessageInfo_default_instance_);
}
inline const ::stark_im::MessageInfo& NotifyNewMessage::msginfo() const {
  // @@protoc_insertion_point(field_get:stark_im.NotifyNewMessage.msginfo)
  return _internal_msginfo();
}
inline ::stark_im::MessageInfo* NotifyNewMessage::release_msginfo() {
  // @@protoc_insertion_point(field_release:stark_im.NotifyNewMessage.msginfo)
  
  ::stark_im::MessageInfo* temp = msginfo_;
  msginfo_ = nullptr;
  return temp;
}
inline ::stark_im::MessageInfo* NotifyNewMessage::_internal_mutable_msginfo() {
  
  if (msginfo_ == nullptr) {
    auto* p = CreateMaybeMessage<::stark_im::MessageInfo>(GetArenaNoVirtual());
    msginfo_ = p;
  }
  return msginfo_;
}
inline ::stark_im::MessageInfo* NotifyNewMessage::mutable_msginfo() {
  // @@protoc_insertion_point(field_mutable:stark_im.NotifyNewMessage.msginfo)
  return _internal_mutable_msginfo();
}
inline void NotifyNewMessage::set_allocated_msginfo(::stark_im::MessageInfo* msginfo) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(msginfo_);
  }
  if (msginfo) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena = nullptr;
    if (message_arena != submessage_arena) {
      msginfo = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, msginfo, submessage_arena);
    }
    
  } else {
    
  }
  msginfo_ = msginfo;
  // @@protoc_insertion_point(field_set_allocated:stark_im.NotifyNewMessage.msginfo)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace stark_im

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_notify_2eproto
